baseURL = "https://iotarch.github.io/iotarch/sbooks"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "sbook site"
theme = "techdoc"

hasCJKLanguage = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
