# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/

defaultMarkdownHandler = "goldmark"
[tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
[goldmark.renderer]
  hardWraps = true
  unsafe = true
  xHTML = true
[highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false