[[main]]
  identifier = "docs"
  name = "文档"
  url = "docs"
  weight = 1

[[main]]
  identifier = "updates"
  name = "更新"
  url = "updates"
  weight = 2

[[main]]
  identifier = "blog"
  name = "博客"
  url = "blog"
  weight = 3