title = "Techdoc Theme"
images = ["images/og-image.png"] # Open graph images are placed in `static/images`

logo = true # Logo that appears in the site navigation bar.
logoText = "Security Book" # Logo text that appears in the site navigation bar.
logoType = "short" # long, short
description = "The Book for Security Audit." # for SEO

version = "0.0.1"

themeOptions = ["light", "dark"] # select options for site color theme

useFaviconGenerator = true # https://www.favicon-generator.org/

enableSearch = true
enableLangChange = true
enableDarkMode = true
enableBreadcrumb = true
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

paginateWindow = 1 # setting it to 1 gives 7 buttons, 2 gives 9, etc. If set 1: [1 ... 4 5 6 ... 356] [1 2 3 4 5 ... 356] etc
taxoPaginate = 13 # items per page
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/crazybber/security-book"


# path name excluded from documentation menu
menu_exclusion = [
    "archives",
    "archive",
    "blog",
    "entry",
    "post",
    "posts",
]

[algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]