name: github pages
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
    - 'public/**'
    - 'resources/**'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 1    # Fetch latest layer and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.70.0'
          extended: true

      - name: Build
        run: hugo   #  --minify
