name: github pages
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
    - 'public/**'
    - 'resources/**'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 1    # Fetch latest layer and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo   #  --minify

      - name: commit
        run: |
          git config --global user.email crazybber@outlook.com
          git config --global user.name Edward
          git add .
          git commit -m "update a book version" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.build_deploy_sbook }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}